on: [issues, pull_request]

jobs:
  origami_project_board_job:
    runs-on: ubuntu-latest
    name: Add new issue/pr to Origami Project Board
    steps:
    - name: Add new issue/pr to Origami Project Board
      id: origami-project-board
      uses: Financial-Times/origami-project-board-action
      with:
        incoming-column-id: 7751116
        origami-fox-access-token: ${{ secrets.ORIGAMI_FOX_ACCESS_TOKEN }}
